import type { PermissionsMap } from '../types/database'

// Tabela de permissões por papel — mantida aqui (fora de AuthContext)
// para que o Vite React Fast Refresh não invalide o módulo de context.
export const ROLE_PERMISSIONS: Record<string, PermissionsMap> = {
  super_admin: {
    dashboard:       { view: true, create: true, edit: true, delete: true, export: true },
    pendencias:      { view: true, create: true, edit: true, delete: true, export: true },
    gamificacao:     { view: true, create: true, edit: true, delete: true, export: true },
    marketing:       { view: true, create: true, edit: true, delete: true, export: true },
    vendas:          { view: true, create: true, edit: true, delete: true, export: true },
    produtos:        { view: true, create: true, edit: true, delete: true, export: true },
    compras:            { view: true, create: true, edit: true, delete: true, export: true },
    requisicoes:        { view: true, create: true, edit: true, delete: true, export: true },
    'req-automaticas':  { view: true, create: true, edit: true, delete: true, export: true },
    estoque:            { view: true, create: true, edit: true, delete: true, export: true },
    fornecedores:       { view: true, create: true, edit: true, delete: true, export: true },
    financeiro:         { view: true, create: true, edit: true, delete: true, export: true },
    cozinha:            { view: true, create: true, edit: true, delete: true, export: true },
    salao:              { view: true, create: true, edit: true, delete: true, export: true },
    usuarios:           { view: true, create: true, edit: true, delete: true, export: true },
    configuracoes:      { view: true, create: true, edit: true, delete: true, export: true },
    'relatorio-cvl':    { view: true, create: true, edit: true, delete: true, export: true },
    ruptura:            { view: true, create: true, edit: true, delete: true, export: true },
    market:             { view: true, create: true, edit: true, delete: true, export: true },
    'compras-agente':   { view: true, create: true, edit: true, delete: true, export: true },
  },
  admin: {
    dashboard:          { view: true, create: true, edit: true, delete: true, export: true },
    pendencias:         { view: true, create: true, edit: true, delete: true, export: true },
    gamificacao:        { view: true, create: true, edit: true, delete: true, export: true },
    marketing:          { view: true, create: true, edit: true, delete: true, export: true },
    vendas:             { view: true, create: true, edit: true, delete: true, export: true },
    produtos:           { view: true, create: true, edit: true, delete: true, export: true },
    compras:            { view: true, create: true, edit: true, delete: true, export: true },
    requisicoes:        { view: true, create: true, edit: true, delete: true, export: true },
    'req-automaticas':  { view: true, create: true, edit: true, delete: true, export: true },
    estoque:            { view: true, create: true, edit: true, delete: true, export: true },
    fornecedores:       { view: true, create: true, edit: true, delete: true, export: true },
    financeiro:         { view: true, create: true, edit: true, delete: true, export: true },
    cozinha:            { view: true, create: true, edit: true, delete: true, export: true },
    salao:              { view: true, create: true, edit: true, delete: true, export: true },
    usuarios:           { view: true, create: true, edit: true, delete: false, export: true },
    configuracoes:      { view: false, create: false, edit: false, delete: false, export: false },
    'relatorio-cvl':    { view: true, create: true, edit: true, delete: true, export: true },
    ruptura:            { view: true, create: true, edit: true, delete: true, export: true },
    market:             { view: true, create: true, edit: true, delete: true, export: true },
    'compras-agente':   { view: true, create: true, edit: true, delete: true, export: true },
  },
  manager: {
    dashboard:          { view: true, create: false, edit: false, delete: false, export: true },
    pendencias:         { view: true, create: true,  edit: true,  delete: false, export: false },
    gamificacao:        { view: true, create: true,  edit: true,  delete: false, export: false },
    marketing:          { view: true, create: true,  edit: true,  delete: false, export: false },
    vendas:             { view: true, create: true,  edit: true,  delete: false, export: true },
    produtos:           { view: true, create: true,  edit: true,  delete: false, export: true },
    compras:            { view: true, create: true,  edit: true,  delete: false, export: false },
    requisicoes:        { view: true, create: true,  edit: true,  delete: false, export: false },
    'req-automaticas':  { view: true, create: true,  edit: true,  delete: false, export: false },
    estoque:            { view: true, create: true,  edit: true,  delete: false, export: true },
    fornecedores:       { view: true, create: true,  edit: true,  delete: false, export: false },
    financeiro:         { view: true, create: false, edit: false, delete: false, export: true },
    cozinha:            { view: true, create: true,  edit: true,  delete: false, export: false },
    salao:              { view: true, create: true,  edit: true,  delete: false, export: false },
    usuarios:           { view: false, create: false, edit: false, delete: false, export: false },
    configuracoes:      { view: false, create: false, edit: false, delete: false, export: false },
    'relatorio-cvl':    { view: true, create: true,  edit: false, delete: false, export: true },
    ruptura:            { view: true, create: true,  edit: true,  delete: false, export: true },
    market:             { view: true, create: true,  edit: true,  delete: false, export: true },
    'compras-agente':   { view: true, create: true,  edit: true,  delete: false, export: true },
  },
  user: {
    dashboard:          { view: true,  create: false, edit: false, delete: false, export: false },
    pendencias:         { view: true,  create: false, edit: false, delete: false, export: false },
    gamificacao:        { view: true,  create: false, edit: false, delete: false, export: false },
    vendas:             { view: true,  create: true,  edit: false, delete: false, export: false },
    produtos:           { view: true,  create: false, edit: false, delete: false, export: false },
    compras:            { view: true,  create: false, edit: false, delete: false, export: false },
    requisicoes:        { view: true,  create: true,  edit: false, delete: false, export: false },
    'req-automaticas':  { view: true,  create: false, edit: false, delete: false, export: false },
    estoque:            { view: true,  create: true,  edit: false, delete: false, export: false },
    fornecedores:       { view: true,  create: false, edit: false, delete: false, export: false },
    cozinha:            { view: true,  create: true,  edit: false, delete: false, export: false },
    salao:              { view: true,  create: true,  edit: false, delete: false, export: false },
    usuarios:           { view: false, create: false, edit: false, delete: false, export: false },
    configuracoes:      { view: false, create: false, edit: false, delete: false, export: false },
    'relatorio-cvl':    { view: false, create: false, edit: false, delete: false, export: false },
    ruptura:            { view: true,  create: true,  edit: false, delete: false, export: false },
    market:             { view: true,  create: false, edit: false, delete: false, export: false },
    'compras-agente':   { view: true,  create: false, edit: false, delete: false, export: false },
  },
  viewer: {
    dashboard:          { view: true,  create: false, edit: false, delete: false, export: false },
    pendencias:         { view: true,  create: false, edit: false, delete: false, export: false },
    gamificacao:        { view: true,  create: false, edit: false, delete: false, export: false },
    produtos:           { view: true,  create: false, edit: false, delete: false, export: false },
    requisicoes:        { view: true,  create: false, edit: false, delete: false, export: false },
    'req-automaticas':  { view: false, create: false, edit: false, delete: false, export: false },
    estoque:            { view: true,  create: false, edit: false, delete: false, export: false },
    fornecedores:       { view: true,  create: false, edit: false, delete: false, export: false },
    financeiro:         { view: true,  create: false, edit: false, delete: false, export: false },
    usuarios:           { view: false, create: false, edit: false, delete: false, export: false },
    configuracoes:      { view: false, create: false, edit: false, delete: false, export: false },
    'relatorio-cvl':    { view: true,  create: false, edit: false, delete: false, export: false },
    ruptura:            { view: true,  create: false, edit: false, delete: false, export: false },
    market:             { view: true,  create: false, edit: false, delete: false, export: false },
    'compras-agente':   { view: true,  create: false, edit: false, delete: false, export: false },
  },
}
